# templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aks-command-app.fullname" . }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "aks-command-app.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "aks-command-app.fullname" . }}
    spec:
      containers:
      - name: aks-command-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.containerPort }}
       
        env:
        - name: TITLE
          value: "{{ .Values.env.title }}"
        - name: ASPNETCORE_ENVIRONMENT
          value: "{{ .Values.env.aspnetcoreEnvironment }}"
       
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aks-command-app.fullname" . }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}  # Expose port 80 to external access
    targetPort: {{ .Values.service.targetPort }}   # Map to port 8080 inside the pod
  selector:
    app: {{ include "aks-command-app.fullname" . }}