namespace: ingress-nginx
ingressName: ingress-datasynchro
secretName: ingress-tls-csi
secretProviderClassName: azure-tls

hosts:
  query: query.cloud-devops-craft.com 
  command: command.cloud-devops-craft.com
 
service:
  query: datasynchro-app-http-app-service
  command: datasynchro-api-http-api-service

volume:
  name: secrets-store-inline
  mountPath: "/mnt/secrets-store"
