namespace: ingress-nginx
ingressName: ingress-datasynchro
secretName: ingress-tls-csi
secretProviderClassName: azure-tls

hosts:
  webapp: app.cloud-devops-craft.com 
  webapi: api.cloud-devops-craft.com
 
service:
  webapp: datasynchro-app-http-app-service
  webapi: datasynchro-api-http-api-service

volume:
  name: secrets-store-inline
  mountPath: "/mnt/secrets-store"
