# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ingress-single
# spec:
#   ingressClassName: nginx
#   defaultBackend:
#     service:
#         name: datasynchro-app-http-app-service
#         port: 
#             number: 80
