apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-path
spec:
  ingressClassName: nginx
  rules:
    - host: ingress.cloud-devops-craft.com
      http:
        paths:
        - path: /red
          pathType: Prefix
          backend:
            service:
              name: logcorner-command-http-api-service
              port: 
                number: 80
        - path: /blue
          pathType: Exact
          backend:
            service:
              name: logcorner-command-http-api-service
              port: 
                number: 80
