apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClassName }}
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  secretObjects:                            # secretObjects defines the desired state of synced K8s secret objects
    - secretName: {{ .Values.secretName }}
      type: kubernetes.io/tls
      data: 
        - objectName: {{ .Values.objectName }}
          key: tls.key
        - objectName: {{ .Values.objectName }}
          key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.userAssignedIdentityID }}  # the user-assigned identity ID
    keyvaultName:  {{ .Values.keyVaultName}}          # the name of the AKV instance
    objects: |
      array:
        - |
          objectName: {{ .Values.objectName }}
          objectType: secret
    tenantId: {{ .Values.tenantId }}                    # the tenant ID of the AKV instance