apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-tls
  namespace: ingress-nginx
spec:
  provider: azure
  secretObjects:                            # secretObjects defines the desired state of synced K8s secret objects
    - secretName: ingress-tls-csi
      type: kubernetes.io/tls
      data: 
        - objectName: logcorner-datasync-cert
          key: tls.key
        - objectName: logcorner-datasync-cert
          key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: d68a85e1-ab1c-4ebf-b858-ac51de914c43
    keyvaultName: kv-shared-edusync-dev                 # the name of the AKV instance
    objects: |
      array:
        - |
          objectName: logcorner-datasync-cert
          objectType: secret
    tenantId: f12a747a-cddf-4426-96ff-ebe055e215a3                    # the tenant ID of the AKV instance