apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name:  {{ .Values.providerClass.certificate.providerClassName }}
spec:
  provider: azure
  secretObjects:                            # secretObjects defines the desired state of synced K8s secret objects
    - secretName: {{ .Values.providerClass.certificate.secretName }}
      type: kubernetes.io/tls
      data: 
        - objectName: {{ .Values.certificateName }} 
          key: tls.key
        - objectName: {{ .Values.certificateName }} 
          key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.userAssignedIdentityID }}
    keyvaultName: {{ .Values.keyvaultName }}                  # the name of the AKV instance
    objects: |
      array:
        - |
          objectName: {{ .Values.certificateName }} 
          objectType: secret
    tenantId: {{ .Values.tenantId }}                     # the tenant ID of the AKV instance
