#ingress-tls.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingressName }}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.hosts.webapi }}
    - {{ .Values.hosts.webapp }}
    secretName: {{ .Values.secretName }}
  rules:
  - host: {{ .Values.hosts.webapi }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.service.webapi }}
            port:
              number: 80
  - host: {{ .Values.hosts.webapp }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.service.webapp }}
            port:
              number: 80